//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGeeksFrontEnd.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserClass", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class UserClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductClass", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class ProductClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcuctReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProuctQtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcuctReview {
            get {
                return this.ProcuctReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcuctReviewField, value) != true)) {
                    this.ProcuctReviewField = value;
                    this.RaisePropertyChanged("ProcuctReview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescriptionField, value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductStatus {
            get {
                return this.ProductStatusField;
            }
            set {
                if ((this.ProductStatusField.Equals(value) != true)) {
                    this.ProductStatusField = value;
                    this.RaisePropertyChanged("ProductStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProuctQty {
            get {
                return this.ProuctQtyField;
            }
            set {
                if ((this.ProuctQtyField.Equals(value) != true)) {
                    this.ProuctQtyField = value;
                    this.RaisePropertyChanged("ProuctQty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ActiveOrNotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGeeksFrontEnd.ServiceReference1.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RegDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ActiveOrNot {
            get {
                return this.ActiveOrNotField;
            }
            set {
                if ((this.ActiveOrNotField.Equals(value) != true)) {
                    this.ActiveOrNotField = value;
                    this.RaisePropertyChanged("ActiveOrNot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGeeksFrontEnd.ServiceReference1.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegDate {
            get {
                return this.RegDateField;
            }
            set {
                if ((this.RegDateField.Equals(value) != true)) {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGeeksFrontEnd.ServiceReference1.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((this.PostalCodeField.Equals(value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGeeksFrontEnd.ServiceReference1.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceClass", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class InvoiceClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double deliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double grossTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double subtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double vatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime day {
            get {
                return this.dayField;
            }
            set {
                if ((this.dayField.Equals(value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double delivery {
            get {
                return this.deliveryField;
            }
            set {
                if ((this.deliveryField.Equals(value) != true)) {
                    this.deliveryField = value;
                    this.RaisePropertyChanged("delivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double grossTotal {
            get {
                return this.grossTotalField;
            }
            set {
                if ((this.grossTotalField.Equals(value) != true)) {
                    this.grossTotalField = value;
                    this.RaisePropertyChanged("grossTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double vat {
            get {
                return this.vatField;
            }
            set {
                if ((this.vatField.Equals(value) != true)) {
                    this.vatField = value;
                    this.RaisePropertyChanged("vat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceProduct", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class InvoiceProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int prodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int prodID {
            get {
                return this.prodIDField;
            }
            set {
                if ((this.prodIDField.Equals(value) != true)) {
                    this.prodIDField = value;
                    this.RaisePropertyChanged("prodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsInCart", Namespace="http://schemas.datacontract.org/2004/07/group_work")]
    [System.SerializableAttribute()]
    public partial class ProductsInCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGroup_Service")]
    public interface IGroup_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Register", ReplyAction="http://tempuri.org/IGroup_Service/RegisterResponse")]
        int Register(WebGeeksFrontEnd.ServiceReference1.UserClass details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Register", ReplyAction="http://tempuri.org/IGroup_Service/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(WebGeeksFrontEnd.ServiceReference1.UserClass details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Login", ReplyAction="http://tempuri.org/IGroup_Service/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Login", ReplyAction="http://tempuri.org/IGroup_Service/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/registered", ReplyAction="http://tempuri.org/IGroup_Service/registeredResponse")]
        bool registered(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/registered", ReplyAction="http://tempuri.org/IGroup_Service/registeredResponse")]
        System.Threading.Tasks.Task<bool> registeredAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/AddProduct", ReplyAction="http://tempuri.org/IGroup_Service/AddProductResponse")]
        int AddProduct(WebGeeksFrontEnd.ServiceReference1.ProductClass product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/AddProduct", ReplyAction="http://tempuri.org/IGroup_Service/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductClass product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/EditProduct", ReplyAction="http://tempuri.org/IGroup_Service/EditProductResponse")]
        int EditProduct(WebGeeksFrontEnd.ServiceReference1.ProductClass product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/EditProduct", ReplyAction="http://tempuri.org/IGroup_Service/EditProductResponse")]
        System.Threading.Tasks.Task<int> EditProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductClass product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getProduct", ReplyAction="http://tempuri.org/IGroup_Service/getProductResponse")]
        WebGeeksFrontEnd.ServiceReference1.ProductClass getProduct(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getProduct", ReplyAction="http://tempuri.org/IGroup_Service/getProductResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.ProductClass> getProductAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Exist", ReplyAction="http://tempuri.org/IGroup_Service/ExistResponse")]
        bool Exist(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/Exist", ReplyAction="http://tempuri.org/IGroup_Service/ExistResponse")]
        System.Threading.Tasks.Task<bool> ExistAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllProduct", ReplyAction="http://tempuri.org/IGroup_Service/getAllProductResponse")]
        WebGeeksFrontEnd.ServiceReference1.Product[] getAllProduct(int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllProduct", ReplyAction="http://tempuri.org/IGroup_Service/getAllProductResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.Product[]> getAllProductAsync(int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/fetchProduct", ReplyAction="http://tempuri.org/IGroup_Service/fetchProductResponse")]
        string fetchProduct(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/fetchProduct", ReplyAction="http://tempuri.org/IGroup_Service/fetchProductResponse")]
        System.Threading.Tasks.Task<string> fetchProductAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getUser", ReplyAction="http://tempuri.org/IGroup_Service/getUserResponse")]
        WebGeeksFrontEnd.ServiceReference1.User getUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getUser", ReplyAction="http://tempuri.org/IGroup_Service/getUserResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.User> getUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getProductByID", ReplyAction="http://tempuri.org/IGroup_Service/getProductByIDResponse")]
        WebGeeksFrontEnd.ServiceReference1.ProductClass getProductByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getProductByID", ReplyAction="http://tempuri.org/IGroup_Service/getProductByIDResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.ProductClass> getProductByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/generateInvoice", ReplyAction="http://tempuri.org/IGroup_Service/generateInvoiceResponse")]
        int generateInvoice(WebGeeksFrontEnd.ServiceReference1.InvoiceClass newInv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/generateInvoice", ReplyAction="http://tempuri.org/IGroup_Service/generateInvoiceResponse")]
        System.Threading.Tasks.Task<int> generateInvoiceAsync(WebGeeksFrontEnd.ServiceReference1.InvoiceClass newInv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getInvoiceID", ReplyAction="http://tempuri.org/IGroup_Service/getInvoiceIDResponse")]
        int getInvoiceID(int userID, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getInvoiceID", ReplyAction="http://tempuri.org/IGroup_Service/getInvoiceIDResponse")]
        System.Threading.Tasks.Task<int> getInvoiceIDAsync(int userID, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllInvoiceProduct", ReplyAction="http://tempuri.org/IGroup_Service/getAllInvoiceProductResponse")]
        WebGeeksFrontEnd.ServiceReference1.InvoiceProduct[] getAllInvoiceProduct(int invID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllInvoiceProduct", ReplyAction="http://tempuri.org/IGroup_Service/getAllInvoiceProductResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceProduct[]> getAllInvoiceProductAsync(int invID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getInvoiceByID", ReplyAction="http://tempuri.org/IGroup_Service/getInvoiceByIDResponse")]
        WebGeeksFrontEnd.ServiceReference1.InvoiceClass getInvoiceByID(int indID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getInvoiceByID", ReplyAction="http://tempuri.org/IGroup_Service/getInvoiceByIDResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceClass> getInvoiceByIDAsync(int indID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/saveOrderProduct", ReplyAction="http://tempuri.org/IGroup_Service/saveOrderProductResponse")]
        bool saveOrderProduct(WebGeeksFrontEnd.ServiceReference1.ProductsInCart[] list, int invID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/saveOrderProduct", ReplyAction="http://tempuri.org/IGroup_Service/saveOrderProductResponse")]
        System.Threading.Tasks.Task<bool> saveOrderProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductsInCart[] list, int invID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/fetchUsers", ReplyAction="http://tempuri.org/IGroup_Service/fetchUsersResponse")]
        int fetchUsers(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/fetchUsers", ReplyAction="http://tempuri.org/IGroup_Service/fetchUsersResponse")]
        System.Threading.Tasks.Task<int> fetchUsersAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllUsers", ReplyAction="http://tempuri.org/IGroup_Service/getAllUsersResponse")]
        WebGeeksFrontEnd.ServiceReference1.User[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllUsers", ReplyAction="http://tempuri.org/IGroup_Service/getAllUsersResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.User[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllInvoices", ReplyAction="http://tempuri.org/IGroup_Service/getAllInvoicesResponse")]
        WebGeeksFrontEnd.ServiceReference1.InvoiceClass[] getAllInvoices(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/getAllInvoices", ReplyAction="http://tempuri.org/IGroup_Service/getAllInvoicesResponse")]
        System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceClass[]> getAllInvoicesAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/editUser", ReplyAction="http://tempuri.org/IGroup_Service/editUserResponse")]
        bool editUser(WebGeeksFrontEnd.ServiceReference1.UserClass userClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/editUser", ReplyAction="http://tempuri.org/IGroup_Service/editUserResponse")]
        System.Threading.Tasks.Task<bool> editUserAsync(WebGeeksFrontEnd.ServiceReference1.UserClass userClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/deleteProduct", ReplyAction="http://tempuri.org/IGroup_Service/deleteProductResponse")]
        bool deleteProduct(string prodName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroup_Service/deleteProduct", ReplyAction="http://tempuri.org/IGroup_Service/deleteProductResponse")]
        System.Threading.Tasks.Task<bool> deleteProductAsync(string prodName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroup_ServiceChannel : WebGeeksFrontEnd.ServiceReference1.IGroup_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Group_ServiceClient : System.ServiceModel.ClientBase<WebGeeksFrontEnd.ServiceReference1.IGroup_Service>, WebGeeksFrontEnd.ServiceReference1.IGroup_Service {
        
        public Group_ServiceClient() {
        }
        
        public Group_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Group_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Group_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Group_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Register(WebGeeksFrontEnd.ServiceReference1.UserClass details) {
            return base.Channel.Register(details);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(WebGeeksFrontEnd.ServiceReference1.UserClass details) {
            return base.Channel.RegisterAsync(details);
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public bool registered(string email, string pass) {
            return base.Channel.registered(email, pass);
        }
        
        public System.Threading.Tasks.Task<bool> registeredAsync(string email, string pass) {
            return base.Channel.registeredAsync(email, pass);
        }
        
        public int AddProduct(WebGeeksFrontEnd.ServiceReference1.ProductClass product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductClass product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public int EditProduct(WebGeeksFrontEnd.ServiceReference1.ProductClass product) {
            return base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> EditProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductClass product) {
            return base.Channel.EditProductAsync(product);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.ProductClass getProduct(string name) {
            return base.Channel.getProduct(name);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.ProductClass> getProductAsync(string name) {
            return base.Channel.getProductAsync(name);
        }
        
        public bool Exist(string name) {
            return base.Channel.Exist(name);
        }
        
        public System.Threading.Tasks.Task<bool> ExistAsync(string name) {
            return base.Channel.ExistAsync(name);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.Product[] getAllProduct(int type) {
            return base.Channel.getAllProduct(type);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.Product[]> getAllProductAsync(int type) {
            return base.Channel.getAllProductAsync(type);
        }
        
        public string fetchProduct(int ID) {
            return base.Channel.fetchProduct(ID);
        }
        
        public System.Threading.Tasks.Task<string> fetchProductAsync(int ID) {
            return base.Channel.fetchProductAsync(ID);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.User getUser(int ID) {
            return base.Channel.getUser(ID);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.User> getUserAsync(int ID) {
            return base.Channel.getUserAsync(ID);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.ProductClass getProductByID(int id) {
            return base.Channel.getProductByID(id);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.ProductClass> getProductByIDAsync(int id) {
            return base.Channel.getProductByIDAsync(id);
        }
        
        public int generateInvoice(WebGeeksFrontEnd.ServiceReference1.InvoiceClass newInv) {
            return base.Channel.generateInvoice(newInv);
        }
        
        public System.Threading.Tasks.Task<int> generateInvoiceAsync(WebGeeksFrontEnd.ServiceReference1.InvoiceClass newInv) {
            return base.Channel.generateInvoiceAsync(newInv);
        }
        
        public int getInvoiceID(int userID, System.DateTime day) {
            return base.Channel.getInvoiceID(userID, day);
        }
        
        public System.Threading.Tasks.Task<int> getInvoiceIDAsync(int userID, System.DateTime day) {
            return base.Channel.getInvoiceIDAsync(userID, day);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.InvoiceProduct[] getAllInvoiceProduct(int invID) {
            return base.Channel.getAllInvoiceProduct(invID);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceProduct[]> getAllInvoiceProductAsync(int invID) {
            return base.Channel.getAllInvoiceProductAsync(invID);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.InvoiceClass getInvoiceByID(int indID) {
            return base.Channel.getInvoiceByID(indID);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceClass> getInvoiceByIDAsync(int indID) {
            return base.Channel.getInvoiceByIDAsync(indID);
        }
        
        public bool saveOrderProduct(WebGeeksFrontEnd.ServiceReference1.ProductsInCart[] list, int invID) {
            return base.Channel.saveOrderProduct(list, invID);
        }
        
        public System.Threading.Tasks.Task<bool> saveOrderProductAsync(WebGeeksFrontEnd.ServiceReference1.ProductsInCart[] list, int invID) {
            return base.Channel.saveOrderProductAsync(list, invID);
        }
        
        public int fetchUsers(System.DateTime date) {
            return base.Channel.fetchUsers(date);
        }
        
        public System.Threading.Tasks.Task<int> fetchUsersAsync(System.DateTime date) {
            return base.Channel.fetchUsersAsync(date);
        }
        
        public WebGeeksFrontEnd.ServiceReference1.User[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.User[]> getAllUsersAsync() {
            return base.Channel.getAllUsersAsync();
        }
        
        public WebGeeksFrontEnd.ServiceReference1.InvoiceClass[] getAllInvoices(int userID) {
            return base.Channel.getAllInvoices(userID);
        }
        
        public System.Threading.Tasks.Task<WebGeeksFrontEnd.ServiceReference1.InvoiceClass[]> getAllInvoicesAsync(int userID) {
            return base.Channel.getAllInvoicesAsync(userID);
        }
        
        public bool editUser(WebGeeksFrontEnd.ServiceReference1.UserClass userClass) {
            return base.Channel.editUser(userClass);
        }
        
        public System.Threading.Tasks.Task<bool> editUserAsync(WebGeeksFrontEnd.ServiceReference1.UserClass userClass) {
            return base.Channel.editUserAsync(userClass);
        }
        
        public bool deleteProduct(string prodName) {
            return base.Channel.deleteProduct(prodName);
        }
        
        public System.Threading.Tasks.Task<bool> deleteProductAsync(string prodName) {
            return base.Channel.deleteProductAsync(prodName);
        }
    }
}
