<?xml version="1.0" encoding="utf-8"?><Database Name="DTB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DTB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DTBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Address_User" Member="Users" ThisKey="Id" OtherKey="AddressID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDay" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="VAT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryFee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TotalExpenditure" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_OrderTracker" Member="OrderTrackers" ThisKey="InvoiceID" OtherKey="InvoiceId" Type="OrderTracker" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTracker" Member="OrderTrackers">
    <Type Name="OrderTracker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_OrderTracker" Member="Invoice" ThisKey="InvoiceId" OtherKey="InvoiceID" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ProductImage" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProuctQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProcuctReview" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CellPhone" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddressID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActiveOrNot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Address_User" Member="Address" ThisKey="AddressID" OtherKey="Id" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
</Database>